### ISSUE TITLE
Deprecate SmartNoise Core Crates

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core#363]
**Tasks**

- [x] Add deprecation notes to the SmartNoise crates
- [x] Change the README text to prominently indicate deprecation and link to the OpenDP library
- [x] Update the README to change any references from  `@opendp.io` to `@opendp.org`, e.g. on the README page
- [ ] Binaries: __These may remain the same__. The key changes needed are above ^

**Crate Pages**
- https://crates.io/crates/smartnoise_validator
- https://crates.io/crates/smartnoise_runtime

**Related PyPI issue**
- https://github.com/opendp/smartnoise-core-python/issues/68
